# Generated by Django 6.0 on 2025-12-18 16:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=100, unique=True, verbose_name='معرف القسم')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية')),
                ('description_ar', models.TextField(verbose_name='الوصف بالعربية')),
                ('description_en', models.TextField(blank=True, verbose_name='الوصف بالإنجليزية')),
                ('question_count', models.IntegerField(default=0, verbose_name='عدد الأسئلة')),
                ('color', models.CharField(default='bg-blue-500', max_length=50, verbose_name='اللون')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['order', 'section_id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=50, unique=True, verbose_name='معرف السؤال')),
                ('text_ar', models.TextField(verbose_name='نص السؤال بالعربية')),
                ('text_en', models.TextField(blank=True, verbose_name='نص السؤال بالإنجليزية')),
                ('text_sv', models.TextField(blank=True, verbose_name='نص السؤال بالسويدية')),
                ('options_ar', models.JSONField(verbose_name='الخيارات بالعربية')),
                ('options_en', models.JSONField(blank=True, null=True, verbose_name='الخيارات بالإنجليزية')),
                ('options_sv', models.JSONField(blank=True, null=True, verbose_name='الخيارات بالسويدية')),
                ('correct_answer', models.IntegerField(verbose_name='رقم الإجابة الصحيحة (0-3)')),
                ('explanation_ar', models.TextField(verbose_name='الشرح بالعربية')),
                ('explanation_en', models.TextField(blank=True, verbose_name='الشرح بالإنجليزية')),
                ('explanation_sv', models.TextField(blank=True, verbose_name='الشرح بالسويدية')),
                ('image_url', models.URLField(blank=True, verbose_name='رابط الصورة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='صورة السؤال')),
                ('difficulty', models.CharField(choices=[('easy', 'سهل'), ('medium', 'متوسط'), ('hard', 'صعب')], default='medium', max_length=20, verbose_name='مستوى الصعوبة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.section', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'الأسئلة',
                'ordering': ['section', 'question_id'],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('full', 'اختبار كامل (65 سؤال)'), ('section', 'اختبار قسم محدد')], max_length=20, verbose_name='نوع الاختبار')),
                ('with_timer', models.BooleanField(default=False, verbose_name='مع مؤقت')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت البدء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإنهاء')),
                ('total_questions', models.IntegerField(verbose_name='إجمالي الأسئلة')),
                ('answered_questions', models.IntegerField(default=0, verbose_name='الأسئلة المجابة')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='الإجابات الصحيحة')),
                ('score_percentage', models.FloatField(default=0.0, verbose_name='النسبة المئوية')),
                ('passed', models.BooleanField(default=False, verbose_name='ناجح')),
                ('time_taken_seconds', models.IntegerField(blank=True, null=True, verbose_name='الوقت المستغرق (بالثواني)')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP المستخدم')),
                ('user_agent', models.TextField(blank=True, verbose_name='معلومات المتصفح')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.section', verbose_name='القسم (إن وجد)')),
            ],
            options={
                'verbose_name': 'محاولة اختبار',
                'verbose_name_plural': 'محاولات الاختبار',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.IntegerField(verbose_name='الإجابة المختارة')),
                ('is_correct', models.BooleanField(verbose_name='صحيحة')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإجابة')),
                ('time_spent_seconds', models.IntegerField(blank=True, null=True, verbose_name='الوقت المستغرق (بالثواني)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question', verbose_name='السؤال')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.testattempt', verbose_name='المحاولة')),
            ],
            options={
                'verbose_name': 'إجابة',
                'verbose_name_plural': 'الإجابات',
                'ordering': ['answered_at'],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
